# Generated by Django 6.0.2 on 2026-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_fix_sample_accents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('medicina_general', 'Medicina General'), ('pediatria', 'Pediatría'), ('odontologia', 'Odontología')], max_length=50),
        ),
    ]
